apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  encrypted: "true"
  iopsPerGB: "10"
  fsType: ext4
  volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
# allowVolumeExpansion: true
# allowedTopologies:
#   - matchLabelExpressions:
#       - key: topology.kubernetes.io/zone
#         values:
#           - us-east-1a
#           - us-east-1b
#           - us-east-1c
#           - us-east-1d
#           - us-east-1e
#           - us-east-1f
# mountOptions:
#   - 