apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "sc"
  resources:
    requests:
      storage: 20Gi
  accessModes: 
    - ReadWriteOnce
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-ebs-dynamic
  labels:
    app: ebs-dynamic
    env: prod
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: ebs-dynamic
          mountPath: /usr/share/nginx/html
  volumes:
    - name: ebs-dynamic
      persistentVolumeClaim:
        claimName: ebs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ebs-dynamic
  labels:
    app: ebs-dynamic
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: ebs-dynamic
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http