#  create EFS volume
#  install driver and add sg rule in EFS SG to allow connection from EKS on 2049
#  add efs policy permission to eks I am role
#  pv, pvc

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0895ef27525176907
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: efs-static
  labels:
    volume-type: efs
    provisioning: static
spec:
  volumeName: efs-static
  volumeMode: Filesystem

  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    volume-type: efs
    provisioning: static
spec:
  containers: 
    - name: nginx
      image: nginx
      volumeMounts:
        - name: efs-static-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-static-volume
      persistentVolumeClaim:
        claimName:
          efs-static
---
apiVersion: v1
kind: Service
metadata:
    name: efs-static
    labels:
      volume-type: efs
      provisioning: static
spec:
  type: LoadBalancer
  selector:
    volume-type: efs
    provisioning: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31007
  

