apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  storageClassName: "efs-sc"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx-efs-dynamic
  labels:
    app: nginx
    env: prod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: efs-dynamic-cliam
          mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-dynamic-cliam
      persistentVolumeClaim:
        claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-efs-dynamic
  labels:
    app: nginx
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: nginx
    env: prod
  ports:
    - port: 80
      targetPort: 80
      name: efs-dynamic-port

