apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux
      command: ["sh", "-c", "sleep 100"]

# both containers are running in the same pod and share the same network namespace
# they can communicate with each other using localhost