apiVersion: v1
kind: Pod
metadata:
  name: env
  labels: 
    project: expense
    envivronment: dev
    concept: env  
spec:
  containers: 
    - name: nginx
      image: nginx
      env:
        - name: DB_Host
          value: mysql
        - name: ROOT_PASSWORD
          value: ExpenseApp@1