apiVersion: v1
kind: Pod
metadata:
  name: resource-limit
  labels: 
    project: expense
    concept: resource-limit
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "0.1"
        limits:
          memory: "128Mi"
          cpu: "0.2"