apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  usrname: c2VraGFy
  password: YWRtaW4xMjM=

# convert the secret to base64
# echo -n "sekhar" | base64

# echo -n "admin123" | base64
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod  
  labels:
    concept: secret
    project: expense
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: secret
              key: usrname
        - name: password
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
      # envFrom:
      #   - secretRef:
      #       name: secret
            