apiVersion: v1
kind: Pod
metadata:
  name: service
  labels:
    concept: service
    project: expense
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    concept: service
    project: expense
spec:
  selector:
    concept: service
    project: expense
  ports:
    - protocal: TCP
      port: 80
      targetPort: 80