apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    concept: lb
    project: expense
spec: 
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    concept: lb
    project: expense
spec:
  selector:
    concept: lb
    project: expense
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx-svc-port