apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    concept: rs
    project: expense
spec:
  replicas: 3
  selector:
    matchLabels:
      concept: rs
      project: expense
  template:
    metadata:
      labels:
        concept: rs
        project: expense
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    concept: rs
    project: expense
spec:
  type: LoadBalancer
  selector:
    concept: rs
    project: expense
  ports:  
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx-svc-port